package graphstream;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class About extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public About() {
        initComponents();
        // Set JFrame vào giữa màn hình
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Image helpIcon = new ImageIcon(Constants.WORKING_DIRECTORY + "/src/images/icon-help.png").getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.setIconImage(helpIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        teamInfo = new javax.swing.JLabel();
        tutorInfo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);

        panel.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(41, 61, 107));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("<html><body>Đề tài: Trực quan hóa<br>mạng trích dẫn bài báo khoa học<br>sử dụng thư viện GraphStream</body></html>");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(title);
        title.setBounds(30, 60, 596, 132);

        teamInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teamInfo.setForeground(new java.awt.Color(41, 61, 107));
        teamInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        teamInfo.setText("<html><body><h3>Nhóm thực hiện: </h3><p>Phạm Nữ Tuyết An - 14520010</p><p>Nguyễn Minh Hiếu - 14520287</p></body></html>");
        teamInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(teamInfo);
        teamInfo.setBounds(370, 240, 194, 90);

        tutorInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tutorInfo.setForeground(new java.awt.Color(41, 61, 107));
        tutorInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tutorInfo.setText("<html><body><h3>Giảng viên hướng dẫn: </h3><p>ThS. Nguyễn Trác Thức</p></body></html>");
        tutorInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(tutorInfo);
        tutorInfo.setBounds(110, 230, 160, 90);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background02.png"))); // NOI18N
        panel.add(background);
        background.setBounds(0, -20, 800, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel teamInfo;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tutorInfo;
    // End of variables declaration//GEN-END:variables
}
