package graphstream;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        // Set JFrame vào giữa màn hình
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        Image appIcon = new ImageIcon(Constants.WORKING_DIRECTORY + "/src/images/app-icon.png").getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH);
        this.setIconImage(appIcon);
        
        searchPaperBtn.setContentAreaFilled(false);
        configBtn.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        searchPaperBtn = new javax.swing.JButton();
        configBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel.setLayout(null);

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(41, 61, 107));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("<html><body>Trực quan hóa<br>mạng trích dẫn bài báo khoa học<br>sử dụng thư viện GraphStream</body></html>");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(title);
        title.setBounds(30, 60, 596, 132);

        searchPaperBtn.setBackground(new java.awt.Color(172, 183, 208));
        searchPaperBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchPaperBtn.setForeground(new java.awt.Color(141, 108, 159));
        searchPaperBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app-icon.png"))); // NOI18N
        searchPaperBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        searchPaperBtn.setBorderPainted(false);
        searchPaperBtn.setMaximumSize(new java.awt.Dimension(90, 90));
        searchPaperBtn.setMinimumSize(new java.awt.Dimension(90, 90));
        searchPaperBtn.setPreferredSize(new java.awt.Dimension(90, 90));
        searchPaperBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPaperBtnActionPerformed(evt);
            }
        });
        panel.add(searchPaperBtn);
        searchPaperBtn.setBounds(390, 230, 67, 67);

        configBtn.setBackground(new java.awt.Color(172, 183, 208));
        configBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        configBtn.setForeground(new java.awt.Color(141, 108, 159));
        configBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-setting.png"))); // NOI18N
        configBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        configBtn.setBorderPainted(false);
        configBtn.setMaximumSize(new java.awt.Dimension(90, 90));
        configBtn.setMinimumSize(new java.awt.Dimension(90, 90));
        configBtn.setPreferredSize(new java.awt.Dimension(90, 90));
        configBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBtnActionPerformed(evt);
            }
        });
        panel.add(configBtn);
        configBtn.setBounds(180, 230, 67, 67);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background02.png"))); // NOI18N
        panel.add(background);
        background.setBounds(-30, -80, 800, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchPaperBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPaperBtnActionPerformed
        // Mở Màn hình tìm kiếm bài báo
        new SearchPaper().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchPaperBtnActionPerformed

    private void configBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBtnActionPerformed
        Configuration config = new Configuration();
        config.setVisible(true);
    }//GEN-LAST:event_configBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton configBtn;
    private javax.swing.JPanel panel;
    private javax.swing.JButton searchPaperBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
